# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stt_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'stt_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11stt_service.proto\x12\rstt_inference\")\n\x13SpeechToTextRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\"$\n\x14SpeechToTextResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2p\n\x13SpeechToTextService\x12Y\n\x0cSpeechToText\x12\".stt_inference.SpeechToTextRequest\x1a#.stt_inference.SpeechToTextResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stt_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPEECHTOTEXTREQUEST']._serialized_start=36
  _globals['_SPEECHTOTEXTREQUEST']._serialized_end=77
  _globals['_SPEECHTOTEXTRESPONSE']._serialized_start=79
  _globals['_SPEECHTOTEXTRESPONSE']._serialized_end=115
  _globals['_SPEECHTOTEXTSERVICE']._serialized_start=117
  _globals['_SPEECHTOTEXTSERVICE']._serialized_end=229
# @@protoc_insertion_point(module_scope)
